### ISSUE TITLE
Is there a way to open files from fterm into the running neovim instance ?

### ISSUE THREAD

**Issue by raul-bns** [numToStr/FTerm.nvim#105]
Hello,

I would like to know if is there a way to open the files from Fterm, to the actual neovim instance that i'm running in a simple way.

Thanks,

**Comment by mayureshsaitwal** [comment]
I believe not, you could use [neovim-remote](https://github.com/mhinz/neovim-remote?tab=readme-ov-file) alongside FTerm.

**Comment by raul-bns** [comment]
Thanks. For the answer.
