### ISSUE TITLE
Border colours are inverted

### ISSUE THREAD

**Issue by maxigaz** [numToStr/FTerm.nvim#19]
Update: For others joining in, I misinterpreted the issue at first. See my next comment below for describing the real problem.

---

With Neovim v0.5.0-dev+1302-g8a93d1028, when I run the following, the border style looks exactly the same as if `single` was replaced with `double`:

```
:lua require'FTerm'.setup({border = 'single'})
```

Adjusting this setting through an init file has the same results.

On the other hand, using the values `none` and `shadow` (taken from `:h nvim_open_win`) works as expected.

**Comment by numToStr** [comment]
IIUC then `double` border is not working for you. But It is working fine for me. As you can see in the image below.
![image](https://user-images.githubusercontent.com/24727447/117402835-c42e8a80-af24-11eb-9c68-56fca2613fbe.png)

**Comment by maxigaz** [comment]
I'm sorry, I was mistaken. Here's how `simple` and `double` look for me, respectively:

![nvim-fterm-1](https://user-images.githubusercontent.com/10419911/117423396-fa6a0b00-af20-11eb-9c68-37c1d3156e4d.png)
![nvim-fterm-2](https://user-images.githubusercontent.com/10419911/117423410-fdfd9200-af20-11eb-9cca-aeee824df45c.png)

So, the real issue is that the border and the area around it seems inverted. (I didn't notice the difference until I moved closer to the screen because of the colour contrast.)

This is how vim-floaterm looks, by the way:

![nvim-fterm-3](https://user-images.githubusercontent.com/10419911/117424323-f68ab880-af21-11eb-8fd2-19261dcf8169.png)

**Comment by numToStr** [comment]
This looks like a highlight issue to me. I've only set `Normal` hi group for the floating window.

**Comment by numToStr** [comment]
@maxigaz Could you please try [border_hi](https://github.com/numToStr/FTerm.nvim/tree/fix/border_hi) branch? And let me know whether your issue is fixed or not.

**Comment by maxigaz** [comment]
I've just tried it and the borders are still inverted.

![nvim-fterm-4](https://user-images.githubusercontent.com/10419911/117568466-a9911880-b0c0-11eb-95b2-e61c5d53df68.png)

**Comment by numToStr** [comment]
Hmm...could you tell me your theme?

**Comment by maxigaz** [comment]
The issue is now fixed in nvim-solarized-lua.
