### ISSUE TITLE
border highlight

### ISSUE THREAD

**Issue by horseinthesky** [numToStr/FTerm.nvim#22]
Is there a way to control border highlighting?

Looks inaccurate by default.
![image](https://user-images.githubusercontent.com/19948672/119463003-fd9b2e80-bd49-11eb-8621-7f8c08e10f39.png)

In Floaterm I do
```
highlight link FloatermBorder Normal
```

Which looks much nicier
![image](https://user-images.githubusercontent.com/19948672/119463146-258a9200-bd4a-11eb-8983-57cb2defe707.png)

**Comment by numToStr** [comment]
This plugin uses neovim's native floating window feature which comes with its own highlights. There was a similar issue #19 raised before but it turns out to be a theme issue.

**Comment by horseinthesky** [comment]
Got it. The default floating windows uses `FloatBorder` group which in turn links to `VertSplit` (in case anybody faces this issue).

Doing
```
highlight VertSplit guibg=NONE ctermbg=NONE
```
makes the windows look nice:
![image](https://user-images.githubusercontent.com/19948672/119486730-3f839f00-bd61-11eb-803d-f106efb11feb.png)
