### ISSUE TITLE
site/pack/packer/start/FTerm.nvim/lua/FTerm/config.lua:30: attempt to index local 'str' (a nil value)

### ISSUE THREAD

**Issue by ttys3** [numToStr/FTerm.nvim#26]
if in docker ( docker run --rm -ti ubuntu:21.04 sh ), there is no `SHELL` env set, the plugin stopped to work:

```
site/pack/packer/start/FTerm.nvim/lua/FTerm/config.lua:30: attempt to index local 'str' (a nil value)
```

**Comment by numToStr** [comment]
Yup, this is expected. Can you change the default `cmd` in the setup and let me know.

**Comment by numToStr** [comment]
Closing for now. Please reopen if the issue is not fixed :)
