### ISSUE TITLE
Lazy Loading

### ISSUE THREAD

**Issue by ashincoder** [numToStr/FTerm.nvim#28]
hello I have an issue. How can I lazy load FTerm. I am trying to find this so that I can implement this on [StarVim](https://github.com/ashincoder/Starvim)

**Comment by numToStr** [comment]
Can  you provide some more context for the `lazy loading`?

**Comment by ashincoder** [comment]
It means that it will be loaded at a specific event, specific key pressed, after another plugin, etc

**Comment by numToStr** [comment]
I am not sure how to achieve that now we have [custom terminal](https://github.com/numToStr/FTerm.nvim#custom-terminal) which expects the plugin to be loaded ahead of time. If you have any suggestions on how to achieve lazy loading i would love to hear that.

**Comment by ashincoder** [comment]
check this code
```lua
	use({
		"ray-x/lsp_signature.nvim",
		event = "InsertEnter",
		config = function()
			require("modules.configs.lsp_sign")
		end,
	})
```

**Comment by ashincoder** [comment]
The given code block means that lsp_signature must be loaded if in insert mode. Otherwise don't load it. I hope this makes sense

**Comment by numToStr** [comment]
Yeah, I am familiar with this `packer.nvim` feature but I am still not sure which event/command can be used to lazy load `FTerm`.

**Comment by ashincoder** [comment]
Yeah maybe with a key like lua`keys = "<space>t`

**Comment by ashincoder** [comment]
But the problem it won't load

**Comment by numToStr** [comment]
Hey @ashincoder, I think this would work.

```lua
use({
    'numToStr/FTerm.nvim',
    event = { 'BufEnter' },
})
```

Please let me know if this works for you.

**Comment by ashincoder** [comment]
Yeah it wirks

**Comment by AckslD** [comment]
Or maybe
```
use({
  'numToStr/FTerm.nvim',
  module = 'FTerm',
})
```
?
