### ISSUE TITLE
black rectangle appearing after window resizing

### ISSUE THREAD

**Issue by salkin-mada** [numToStr/FTerm.nvim#3]
`nvim` v0.5.0-865-gfb52790d1
`sway` version 1.5.1
`alacritty` 0.6.0 (04cbf767)
Arch 5.9.1-rt20-1-rt

this sort of stuff happens when I resize my window (for bigger) after calling `:FTermToggle` on opening `nvim`.

![scrn-2020-12-11-04-29-32](https://user-images.githubusercontent.com/12082586/101858381-c8b76880-3b69-11eb-914d-d910412a289e.png)

and this sort of stuff happens when I resize my window (for smaller) after calling `:FTermToggle` on opening `nvim`.

![scrn-2020-12-11-04-43-45](https://user-images.githubusercontent.com/12082586/101859102-5051a700-3b6b-11eb-8cde-25d1d88a80d6.png)

in both cases i have to toggle FTerm off/on to create the issue.

can you reproduce on your wm / system ?

and thanks for a nice plugin.

**Comment by numToStr** [comment]
Ahh, I am aware of the second one and I never faced the black rectangle issue. This is how it looks like on my DE.

![image](https://user-images.githubusercontent.com/24727447/101863838-c40aa880-3b99-11eb-9b99-088c6ee2224f.png)

Currently, I don't know how to fix it. The only thing you can do is to exit the terminal and open it again.

**Comment by DONofDESTROY** [comment]
I think the this could be used `│` instead of current vertical line , and I am not sure that this is been fixed by you, I am not facing this issue

**Comment by numToStr** [comment]
I don't remember fixing this. Although I did some changes to the borders to make it customizable.

I suppose if you are not facing this issue anymore. You can close the issue :)
