### ISSUE TITLE
How to toggle the terminal?

### ISSUE THREAD

**Issue by z0mbix** [numToStr/FTerm.nvim#30]
I've installed FTerm and am using `lua require('FTerm').toggle()` to toggle the terminal, which opens it, but once the terminal is open, how to I toggle it closed again as I can't enter neovim's command mode inside the terminal?

**Comment by delphinus** [comment]
Use `<Cmd>` to run commands from any modes. So you can toggle FTerm with these mappings below.

```vim
tnoremap <C-t> <Cmd>lua require'FTerm'.toggle()<CR>
nnoremap <C-t> <Cmd>lua require'FTerm'.toggle()<CR>
```

See https://neovim.io/doc/user/map.html#%3CCmd%3E

**Comment by delphinus** [comment]
In addition to that, you can run into the command mode from terminals with this map: `<C-\><C-n>:`

https://neovim.io/doc/user/intro.html#CTRL-\_CTRL-N

**Comment by z0mbix** [comment]
I had no idea about `tnoremap`. Thanks, this works perfectly 😃
