### ISSUE TITLE
Document how to make a file manager wrapper

### ISSUE THREAD

**Issue by arafatamim** [numToStr/FTerm.nvim#40]
I intend to use this to create a wrapper to TUI file managers like `ranger` & `lf`, where opening a file in the terminal would open it in a new buffer. I have no idea how to implement something like this though. Any pointers?
Reference: https://github.com/ptzz/lf.vim

**Comment by numToStr** [comment]
You won't be able to use `FTerm` as a wrapper. As every cli tools is different and your use case is out of scope for this plugin.

**Comment by arafatamim** [comment]
Alright thanks for the answer. Looks like I'm gonna have to stick with floaterm.
