### ISSUE TITLE
option for not start in insert mode

### ISSUE THREAD

**Issue by grimgort** [numToStr/FTerm.nvim#48]
Hello,
Is it possible to add an option for no start in insert mode.
Jump this line :
![image](https://user-images.githubusercontent.com/44238325/144439202-567aad35-fb92-4791-bc16-aded1849413c.png)
Thanks

**Comment by numToStr** [comment]
@grimgort What's your use case?

**Comment by grimgort** [comment]
when i compile c++ code,  i can't switch between line and error compile message wrote in terminal, because insert mode go to last line from this

**Comment by numToStr** [comment]
@grimgort You can always go to normal mode by pressing `<C-\><C-o>`
