### ISSUE TITLE
Will this plugin have multiple terminal float windows

### ISSUE THREAD

**Issue by DONofDESTROY** [numToStr/FTerm.nvim#5]
Hey hi, will this plugin get multiple terminal float windows just like vim-floaterm

**Comment by numToStr** [comment]
I am not sure about that. I haven't found myself a use case for multiple terminals inside neovim.

What's your use case? Just curious.

**Comment by DONofDESTROY** [comment]
I am still a learner in webdev, I can launch live server in one terminal and maybe launch prettier or sass compiler in another terminal window

**Comment by numToStr** [comment]
IMO any long-running process inside the neovim terminal tends to slowdown neovim, at least that's the case with me. I wouldn't suggest you launch the server in another tab.

**Comment by DONofDESTROY** [comment]
ok, I am not aware of that
