### ISSUE TITLE
[Question] Add vifm-buit in

### ISSUE THREAD

**Issue by TornaxO7** [numToStr/FTerm.nvim#56]
Hi! I've got a little question. I'm using the `vifm` file manager and I'm wondering if I should add a PR for a default vifm-floating-terminal. What do you think about that?

**Comment by numToStr** [comment]
To be honest I want this plugin to be dead simple and with a "do-one-job" mindset. So there is no point in adding support for external programs in the core :)

**Comment by TornaxO7** [comment]
Understandable. Thank you gor your response :)
