### ISSUE TITLE
how to use fterm

### ISSUE THREAD

**Issue by SongTianxian9** [numToStr/FTerm.nvim#57]
I want known how can i get something done like `:FloatermNew --autoclose=0 gcc % -o %< && ./%:h`, i know there's `require("FTerm").run` but i don't know , how can i get current buffer name , current buffer name without extension , current line number or something else . anyone knows if there a help manual?

**Comment by numToStr** [comment]
Have a look at the lua API `:h api`

**Comment by SongTianxian9** [comment]
> 看看 lua API`:h api`

thank you for your reply and your work, i have not find much more useful information for there(just you can use nvim_buf_get_name() to get current buffer name), now i use `vim.fn.expand("%:p:r")` and similar things. thanks again!!

**Comment by numToStr** [comment]
I am glad that it worked out for you. Nothing is better than reading vim help :)
