### ISSUE TITLE
FTerm crashes on Windows due to latest commit

### ISSUE THREAD

**Issue by figurae** [numToStr/FTerm.nvim#64]
Hi! I mean a58dc7a5cd1b9a55d1cdf5e869d3986b9f188e86. I tried setting `cmd` in my `require'FTerm'.setup()`, but it didn't work because it always asserts `os.getenv('SHELL')` regardless of what I set `cmd` to. Reverting line 26 in `utils.lua` makes it work again.

**Comment by figurae** [comment]
Thanks, everything's fine now. But it works regardless of `config.cmd` in my init, It works without it, and it works when set to `nil` (which is what it was before since Windows doesn't have $SHELL).

**Comment by Lindenbyte** [comment]
Also experienced similar effects on Windows where I got the following error and needed to set config.cmd explicitly to point to PowerShell.exe. (Tried cmd.exe as well but didn't change the result or error)

Error on any FTerm function: `[FTerm] $SHELL is not present! Please provide a shell ('config.cmd') to use.`
Config: `require('FTerm').setup({
    cmd  = 'C:/Windows/System32/WindowsPowerShell/v1.0/powershell.exe'
})`

Don't know if this would be of any interesting to include in default setup, but decided to let you guys know of my experience just in case. 👍
