### ISSUE TITLE
run() function stopped working

### ISSUE THREAD

**Issue by dzfrias** [numToStr/FTerm.nvim#65]
## Problem
When a new terminal is created with the run() function, instead of running the inputted command, something like: `$ table: HEXNUM` is run instead.

After doing some testing, this broke in commit f3fb0fe4d2ada78c3449acf7849dd52ea46a6c13.

## Recreating
With a fresh version of FTerm.nvim, put this in your init.vim:
```vim
nnoremap <leader>r :w<CR> :lua require('FTerm').run({'echo', 'hello'})<CR>
```
or whatever the equivalent is in Lua.

Now when <leader>r is pressed, the command doesn't work and behaves as described in the 'Problem' section.

After going back to the commit before f3fb0fe4d2ada78c3449acf7849dd52ea46a6c13, everything worked again.

**Comment by numToStr** [comment]
Thanks for the report. Should be fixed by https://github.com/numToStr/FTerm.nvim/commit/0080eaeca3f3ed62d3a1b3d0f84b077dacf88053

**Comment by dzfrias** [comment]
Great! Thanks
