### ISSUE TITLE
Cursor stuck out of window as of latest commit

### ISSUE THREAD

**Issue by dzfrias** [numToStr/FTerm.nvim#66]
## Problem
After commit 0080eaeca3f3ed62d3a1b3d0f84b077dacf88053, whenever I enter a new terminal, my cursor gets stuck outside of the floating window.

## Recreating
Just open any terminal window and try to enter something into the prompt.

**Comment by numToStr** [comment]
I tried it before and it was working fine for me. Would you mind telling me the command that you are running?

**Comment by dzfrias** [comment]
After further investigation, it appears to only be a problem when editing Go files, so it might be vim-go. I'll close this issue because I don't think there's much you can do about it.
