### ISSUE TITLE
Feat: Pre start in background

### ISSUE THREAD

**Issue by adelarsq** [numToStr/FTerm.nvim#69]
The first time that a terminal window is opened takes some seconds to be able to use, mainly if you have a lot of configurations to start the terminal.
Would be nice a pre start feature, without to show a terminal, starting in background.

**Comment by numToStr** [comment]
> takes some seconds to be able to use

This is never the case for me. In fact, terminal buffer opens instantaneous, the slowness comes from the shell I suppose.

> Would be nice a pre start feature, without to show a terminal, starting in background.

What does this actually mean?

**Comment by numToStr** [comment]
You can add a `VimEnter` and use `fterm:open():close()` but you will definitely see flickers.

But I would recommend to make your shell load faster using lazy load and such, but I guess you already know it.

**Comment by adelarsq** [comment]
I am not familiar with this syntax `fterm:open():close()` but I tried this an works nicely:

```
augroup prestart_terminal
    au!
    au VimEnter * lua require('FTerm').open();require('FTerm').close(); 
augroup END
```

The reason is that I still use both Neovim and Vim.

> ...will definitely see flickers

I notice only one, that It stays on insert mode after Neovim starts. But can be a conflict with another plugin. I can live with that 😄 

> I would recommend to make your shell load faster using lazy load and such...

Yes, on Zsh I already use lazy load but my PowerShell still need some work.

Thanks for the help. I will close this issue, since can be solved with the previous config.

**Comment by tristone13th** [comment]
> require('FTerm').open();require('FTerm').close();

A very nice workaround, thanks!
