### ISSUE TITLE
Question on escape key!

### ISSUE THREAD

**Issue by sozoalvin** [numToStr/FTerm.nvim#70]
Hi! Coming from reddit. Not sure if this is the best place to ask something. 

If I toggle the term, what does pressing escape do? Does it shift the focus to the buffer that was last opened before opening a floating term? 

If yes, can this behavior be changed? E.g. disabling esc key in the floating term

I'm asking because I'll like to use fterm with lazygit and would need to use esc there.. many thanks in advance for your help!!

**Comment by numToStr** [comment]
`<ESC>` does nothing unless you bind it via `:tnoremap` or via lazygit. I would suggest you to try and see for yourself.
