### ISSUE TITLE
How can I make the terminal automatically place itself in the directory of the file I am working on?

### ISSUE THREAD

**Issue by luisnrz1995** [numToStr/FTerm.nvim#72]
![2022-10-20_01:53:31](https://user-images.githubusercontent.com/44538727/196877354-1b1e58b8-8dc1-407e-9fce-0faa78d22670.png)

I really like this plugin, but I would like to be able to make the terminal open in the directory I am working in and not in the $HOME path.

**Comment by numToStr** [comment]
`FTerm` should open terminal relative to `:h :pwd`. Please check what's your `:pwd` when you are working on a project?

**Comment by aidanlw505** [comment]
Putting `vim.opt.autochdir = true` or `set autochdir` in your config should work.

**Comment by luisnrz1995** [comment]
> Putting `vim.opt.autochdir = true` or `set autochdir` in your config should work.

Thanks a lot, it works!!

**Comment by numToStr** [comment]
Feel free to close this if your issue is resolved.

**Comment by numToStr** [comment]
Feel free to close this if your issue is resolved.
